---
# file: tasks/main.yml

- import_tasks: multi_os.yml
  tags:
    - test_nagios_pnp4nagios

- name: Include nagios server Variables
  include_vars: nagios_vars.yml
  tags:
    - test_nagios_pnp4nagios

- import_tasks: config_pnp.yml

- import_tasks: config_notifications.yml

- import_tasks: config_nagios.yml

- import_tasks: supervisor.yml

- meta: flush_handlers

- import_tasks: tests.yml
  tags:
    - test_nagios_pnp4nagios
