
- name: Install supervisor
  package: 
    name: supervisor
    state: latest

- name: configure supervisor logrotate
  template:
    src: supervisor_logrotate.j2
    dest: /etc/logrotate.d/supervisor

- name: ensure supervisor is running
  service:
    name: supervisor
    state: started

- name: ensure supervisor is enabled
  service:
    name: supervisor
    enabled: yes
    
- name: configure npcd supervisor service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "npcd-supervisor.j2", dest: "/etc/supervisor/conf.d/npcd-service.conf" }
  notify: 
    - restart supervisor
    - Restart NPCD

- name: disable SysV npcd service 
  service:
    name: npcd
    state: stopped
    enabled: no
 
- name: ensure handlers runs before continue
  meta: flush_handlers
